/// Types and initial data used for constructing [KEYMAP].
pub mod init {
    /// Alias for the NestedKey used for the [Context].
    pub type NestedKey = crate::key::composite::DefaultNestableKey;

    /// Types used in Composite keys.
    pub type CompositeImpl = crate::key::composite::CompositeImpl<NestedKey>;

    /// Alias for Context type; i.e. [crate::key::context::Context] with generics.
    pub type Context = crate::key::composite::Context;

    /// Alias for Event type; i.e. [crate::key::context::Event].
    pub type Event = crate::key::composite::Event;

    /// Initial [Context] value.
    pub const CONTEXT: Context = crate::key::composite::Context {
        layer_context: crate::key::layered::Context {
            active_layers: [false; crate::key::layered::LAYER_COUNT],
        },
    };

    crate::tuples::define_keys!(2);

    /// Alias for a [tuples] KeysN type, as generated by keymap.ncl.
    pub type KeyDefinitionsType = Keys2<
        crate::key::tap_hold::Key<
            crate::key::composite::Key<
                crate::key::composite::CompositeImpl<crate::key::keyboard::Key>,
            >,
        >,
        crate::key::layered::LayeredKey<crate::key::keyboard::Key>,
        Context,
        Event,
    >;

    /// A [tuples] KeysN value with keys, as generated by keymap.ncl.
    pub const KEY_DEFINITIONS: KeyDefinitionsType = Keys2::new((
        crate::key::tap_hold::Key::new(
            crate::key::composite::Key::keyboard(crate::key::keyboard::Key::new(4)),
            crate::key::composite::Key::layer_modifier(crate::key::layered::ModifierKey::Hold(0)),
        ),
        crate::key::layered::LayeredKey::new(
            crate::key::keyboard::Key::new(5),
            [Some(crate::key::keyboard::Key::new(6))],
        ),
    ));
}
