board := "ncl/boards/ch32x-48.ncl"

default: build

_libsmartkeymap:
  make libsmartkeymap

cmake-generate: _libsmartkeymap
  cmake \
    -S . \
    -B build \
    --toolchain=../../toolchains/riscv-none-elf.cmake \
    -D CMAKE_EXPORT_COMPILE_COMMANDS=1 \
    -D BOARD={{board}}

build: cmake-generate
  cmake --build build

await-bootloader:
  timeout 30 ./scripts/wchisp-await-bootloader.sh

flash: build await-bootloader
  wchisp flash build/usb-device-compositekm.hex
