board := "ncl/boards/wabble-60.ncl"

default: build

_libsmartkeymap:
  make libsmartkeymap

cmake-generate: _libsmartkeymap
  cmake \
    -S . \
    -B build \
    --toolchain=../../toolchains/riscv-none-elf.cmake \
    -D BOARD={{board}}

build: cmake-generate
  cmake --build build

await-bootloader:
  timeout 30 ./scripts/wchisp-await-bootloader.sh

flash: build await-bootloader
  wchisp flash build/HID_Keyboard.hex
