/// Types and initial data used for constructing [KEYMAP].
pub mod init {
    const NUM_LAYERS: usize = 0;

    /// Alias for layers impl.
    pub type LayersImpl = crate::key::layered::ArrayImpl<NUM_LAYERS>;

    /// Alias for the NestedKey used for the [Context].
    pub type NestedKey = crate::key::composite::DefaultNestableKey;

    /// Types used in Composite keys.
    pub type CompositeImpl = crate::key::composite::CompositeImpl<NestedKey, LayersImpl>;

    /// Alias for Context type; i.e. [crate::key::context::Context] with generics.
    pub type Context = crate::key::composite::Context<LayersImpl>;

    /// Alias for Event type; i.e. [crate::key::context::Event].
    pub type Event = crate::key::composite::Event;

    /// Initial [Context] value.
    pub const CONTEXT: Context = crate::key::composite::Context {
        layer_context: crate::key::layered::Context {
            active_layers: [false; NUM_LAYERS],
        },
    };

    crate::tuples::define_keys!(60);

    /// Alias for a [tuples] KeysN type, as generated by keymap.ncl.
    pub type KeyDefinitionsType = Keys60<
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::tap_hold::Key<crate::key::keyboard::Key>,
        crate::key::tap_hold::Key<crate::key::keyboard::Key>,
        crate::key::tap_hold::Key<crate::key::keyboard::Key>,
        crate::key::tap_hold::Key<crate::key::keyboard::Key>,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::tap_hold::Key<crate::key::keyboard::Key>,
        crate::key::tap_hold::Key<crate::key::keyboard::Key>,
        crate::key::tap_hold::Key<crate::key::keyboard::Key>,
        crate::key::tap_hold::Key<crate::key::keyboard::Key>,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        crate::key::keyboard::Key,
        Context,
        Event,
    >;

    /// A [tuples] KeysN value with keys, as generated by keymap.ncl.
    pub const KEY_DEFINITIONS: KeyDefinitionsType = Keys60::new((
        crate::key::keyboard::Key(53),
        crate::key::keyboard::Key(30),
        crate::key::keyboard::Key(31),
        crate::key::keyboard::Key(32),
        crate::key::keyboard::Key(33),
        crate::key::keyboard::Key(34),
        crate::key::keyboard::Key(35),
        crate::key::keyboard::Key(36),
        crate::key::keyboard::Key(37),
        crate::key::keyboard::Key(38),
        crate::key::keyboard::Key(39),
        crate::key::keyboard::Key(76),
        crate::key::keyboard::Key(43),
        crate::key::keyboard::Key(52),
        crate::key::keyboard::Key(54),
        crate::key::keyboard::Key(55),
        crate::key::keyboard::Key(19),
        crate::key::keyboard::Key(28),
        crate::key::keyboard::Key(9),
        crate::key::keyboard::Key(10),
        crate::key::keyboard::Key(6),
        crate::key::keyboard::Key(21),
        crate::key::keyboard::Key(15),
        crate::key::keyboard::Key(42),
        crate::key::keyboard::Key(41),
        crate::key::tap_hold::Key {
            hold: crate::key::keyboard::Key(226),
            tap: crate::key::keyboard::Key(4),
        },
        crate::key::tap_hold::Key {
            hold: crate::key::keyboard::Key(227),
            tap: crate::key::keyboard::Key(18),
        },
        crate::key::tap_hold::Key {
            hold: crate::key::keyboard::Key(224),
            tap: crate::key::keyboard::Key(8),
        },
        crate::key::tap_hold::Key {
            hold: crate::key::keyboard::Key(225),
            tap: crate::key::keyboard::Key(24),
        },
        crate::key::keyboard::Key(12),
        crate::key::keyboard::Key(7),
        crate::key::tap_hold::Key {
            hold: crate::key::keyboard::Key(229),
            tap: crate::key::keyboard::Key(11),
        },
        crate::key::tap_hold::Key {
            hold: crate::key::keyboard::Key(228),
            tap: crate::key::keyboard::Key(23),
        },
        crate::key::tap_hold::Key {
            hold: crate::key::keyboard::Key(231),
            tap: crate::key::keyboard::Key(17),
        },
        crate::key::tap_hold::Key {
            hold: crate::key::keyboard::Key(230),
            tap: crate::key::keyboard::Key(22),
        },
        crate::key::keyboard::Key(40),
        crate::key::keyboard::Key(225),
        crate::key::keyboard::Key(51),
        crate::key::keyboard::Key(20),
        crate::key::keyboard::Key(13),
        crate::key::keyboard::Key(14),
        crate::key::keyboard::Key(27),
        crate::key::keyboard::Key(5),
        crate::key::keyboard::Key(16),
        crate::key::keyboard::Key(26),
        crate::key::keyboard::Key(25),
        crate::key::keyboard::Key(29),
        crate::key::keyboard::Key(229),
        crate::key::keyboard::Key(224),
        crate::key::keyboard::Key(227),
        crate::key::keyboard::Key(226),
        crate::key::keyboard::Key(43),
        crate::key::keyboard::Key(41),
        crate::key::keyboard::Key(44),
        crate::key::keyboard::Key(42),
        crate::key::keyboard::Key(40),
        crate::key::keyboard::Key(76),
        crate::key::keyboard::Key(230),
        crate::key::keyboard::Key(231),
        crate::key::keyboard::Key(228),
    ));
}
