name: Setup Nickel
description: Install the pinned Nickel CLI binary

inputs:
  version:
    description: Nickel release version
    required: false
    default: "1.16.0"

runs:
  using: composite
  steps:
    - name: Install nickel
      shell: bash
      run: |
        wget -q "https://github.com/tweag/nickel/releases/download/${{ inputs.version }}/nickel-x86_64-linux"
        chmod +x ./nickel-x86_64-linux
        sudo cp ./nickel-x86_64-linux /usr/bin/nickel
