_ws_racket := "/workspace/racket-install/racket/bin"
export PATH := (if path_exists(_ws_racket) == "true" { _ws_racket + ":" } else { "" }) + env("PATH")

test:
    ./run.sh test

# just viz layout=48key-basic
viz layout:
    ./run.sh viz {{layout}}

# just viz-path layout=/path/to/layout.rhm exporter=/path/to/export-legend.ncl
viz-path layout exporter="":
    ./run.sh viz-path {{layout}} {{exporter}}

artifacts:
    ./run.sh artifacts

png:
    ./run.sh png

all: test artifacts
