name: Nickel Codegen

env:
  NICKEL_VERSION: 1.16.0

on:
  push:
    branches:
      - master
    paths:
      - 'ncl/**'
      - 'src/**'
      - 'tests/ncl/**'
  pull_request:
    branches:
      - '*'
    paths:
      - 'ncl/**'
      - 'src/**'
      - 'tests/ncl/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ncl-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Nickel
        uses: ./.github/actions/setup-nickel
        with:
          version: ${{ env.NICKEL_VERSION }}

      - name: Run Nickel checks
        run: make test-ncl-checks

  ncl-snapshots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Nickel
        uses: ./.github/actions/setup-nickel
        with:
          version: ${{ env.NICKEL_VERSION }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gawk pandoc
          rustup target add riscv32imac-unknown-none-elf

      - name: Rust cache
        uses: swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2.9.1
        with:
          shared-key: nickel-codegen
          cache-targets: riscv32imac-unknown-none-elf

      - name: Run Nickel snapshot fixtures
        run: make test-ncl-snapshots

      - name: Generate feature docs
        run: ./features/scripts/generate-doc.sh
