name: Nickel Codegen

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  cargo-build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install nickel
        run: |
          wget https://github.com/tweag/nickel/releases/download/1.9.1/nickel-x86_64-linux
          chmod +x ./nickel-x86_64-linux
          sudo cp ./nickel-x86_64-linux /usr/bin/nickel

      - name: Install dependencies
        run: |
          rustup target add riscv32imac-unknown-none-elf

      - name: Run Nickel tests
        run: |
          ./ncl/scripts/run-tests.sh
