name: Nickel Codegen

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  cargo-build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          rustup target add riscv32imac-unknown-none-elf
          cargo install nickel-lang-cli

      - name: Run Nickel tests
        run: |
          ./ncl/scripts/run-tests.sh
