name: Rust Checks (STM32F4)

env:
  NICKEL_VERSION: 1.16.0

on:
  push:
    branches:
      - master
    paths:
      - '.cargo/config.toml'
      - 'Cargo.*'
      - 'ld/stm32f4xx-tinyuf2/*'
      - 'ncl/**/*.ncl'
      - 'stm32f4-rtic-smart-keyboard/**'
      - 'src/**/*.rs'
      - 'smart-keymap-nickel-helper/**'
      - 'keyberon-smart-keyboard/**'
  pull_request:
    branches:
      - '*'
    paths:
      - '.cargo/config.toml'
      - 'Cargo.*'
      - 'ld/stm32f4xx-tinyuf2/*'
      - 'ncl/**/*.ncl'
      - 'stm32f4-rtic-smart-keyboard/**'
      - 'src/**/*.rs'
      - 'smart-keymap-nickel-helper/**'
      - 'keyberon-smart-keyboard/**'

jobs:
  cargo-build-target-thumbv7em-none-eabihf:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Nickel
        uses: ./.github/actions/setup-nickel
        with:
          version: ${{ env.NICKEL_VERSION }}

      - name: Rust Add Target
        run: rustup target add thumbv7em-none-eabihf

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          shared-key: rust-stm32f4
          cache-targets: thumbv7em-none-eabihf

      - name: Run Cargo Build
        run: cargo build --release --target=thumbv7em-none-eabihf --no-default-features

      - name: Run Cargo Build (keyberon-smart-keymap)
        run: cargo build --release --target=thumbv7em-none-eabihf --package=keyberon-smart-keyboard

      - name: Run Cargo Build (stm32f4-rtic-smart-keyboard)
        run: cargo build --release --target=thumbv7em-none-eabihf --package=stm32f4-rtic-smart-keyboard

      - name: Run Cargo Build (stm32f4-rtic-smart-keyboard, ex=minif4_36-rev2021_4-lhs)
        run: cargo build --release --target=thumbv7em-none-eabihf --package=stm32f4-rtic-smart-keyboard --example=minif4_36-rev2021_4-lhs

      - name: Run Cargo Build (stm32f4-rtic-smart-keyboard, ex=minif4_36-rev2021_4-rhs)
        run: cargo build --release --target=thumbv7em-none-eabihf --package=stm32f4-rtic-smart-keyboard --example=minif4_36-rev2021_4-rhs

      - name: Run Cargo Doc
        run: |
          cargo doc \
            --no-default-features \
            --package=stm32f4-rtic-smart-keyboard \
            --package=smart-keymap \
            --package=keyberon-smart-keyboard
        env:
          RUSTDOCFLAGS: --deny warnings
