name: C Checks

on:
  push:
    branches:
      - master
    paths:
      - 'ncl/**/*.ncl'
      - 'src/**'
      - 'smart_keymap/**'
      - 'tests/ceedling/**'
  pull_request:
    branches:
      - '*'
    paths:
      - 'ncl/**/*.ncl'
      - 'src/**'
      - 'smart_keymap/**'
      - 'tests/ceedling/**'

jobs:
  unity-test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install nickel
        run: |
          wget https://github.com/tweag/nickel/releases/download/1.9.1/nickel-x86_64-linux
          chmod +x ./nickel-x86_64-linux
          sudo cp ./nickel-x86_64-linux /usr/bin/nickel

      - name: Install dependencies
        run: |
          export PATH=$(gem environment user_gemhome)/bin:$PATH
          export GEM_HOME=$(gem environment user_gemhome)
          gem install bundler --user-install
          bundle install
          wget https://github.com/mozilla/cbindgen/releases/download/0.28.0/cbindgen
          chmod +x ./cbindgen
          sudo cp ./cbindgen /usr/bin/cbindgen

      - name: Run Ceedling Tests
        run: |
          export PATH=$(gem environment user_gemhome)/bin:$PATH
          make test-ceedling
