name: C Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  unity-test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          export PATH=$(gem environment user_gemhome)/bin:$PATH
          export GEM_HOME=$(gem environment user_gemhome)
          gem install bundler --user-install
          bundle install
          cargo install --force cbindgen

      - name: Run Tests
        run: |
          export PATH=$(gem environment user_gemhome)/bin:$PATH
          make
          make test
