name: C Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  unity-test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install meson
          cargo install --force cbindgen

      - name: Run Tests
        run: |
          make
          make test
